import React from 'react'

const Home = () => {
    return (
        <div className='bg-gray-300 p-6'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa placeat ratione pariatur harum rem? Ipsum nesciunt nam iusto tempore similique autem iste repellendus maxime laudantium veritatis, quasi voluptatibus nihil, itaque sit voluptatem et odio quas ullam inventore facilis tempora asperiores. Debitis error tempora odit beatae animi ducimus, illo quos aliquid ad, qui distinctio exercitationem minus eaque, reprehenderit nemo doloribus perferendis laboriosam magnam itaque. Ad repellendus in mollitia, ab similique eius veritatis facere debitis quia esse, non harum dolores! Sint nesciunt vero doloremque odio neque ab reiciendis unde saepe fugit reprehenderit, recusandae magni sunt autem est, maxime repellat impedit eius dolor quia, atque facere cupiditate assumenda. Modi magnam similique eos ea quod. Fuga natus eveniet assumenda dolorum magni, culpa, rem dolor consequuntur, sed at dolore. In debitis libero qui pariatur laborum consequuntur! Placeat aperiam blanditiis expedita perspiciatis? Vitae veniam tempora accusamus omnis, eos corporis ut? Officiis veniam at facilis temporibus, voluptatum quos mollitia quo recusandae? Ab maiores quasi blanditiis dicta reprehenderit sit natus doloremque facere atque pariatur. Cum est provident deleniti ducimus hic libero laborum fuga tempora eaque nesciunt repellendus rem, quam quidem reiciendis suscipit, perspiciatis fugiat laboriosam. Porro dicta tempore fugit similique nam quod dolores assumenda harum quis quia dolorem, praesentium hic consectetur veritatis maiores ratione deleniti corporis modi. Blanditiis eveniet ex, alias earum quae doloribus dolorum, excepturi nulla ad rerum deleniti in inventore saepe dolore aspernatur voluptatum quasi modi sapiente facilis explicabo quidem porro! Laudantium non animi beatae eligendi sapiente alias tenetur. Quaerat unde rerum cupiditate harum, nobis, accusantium, repellat debitis consectetur dolor natus iusto vitae quidem maxime. Iusto illum officiis aperiam, sit hic ipsam ducimus eum itaque esse eius vitae debitis nobis a cum quis distinctio. Repudiandae placeat magni provident nobis soluta illum amet? Obcaecati, doloribus culpa aliquid quis sint eum error assumenda dolorum totam praesentium harum quia nesciunt possimus nobis quos rem dolorem eos quas tempore, veniam quo, officiis nisi? Pariatur eius obcaecati inventore molestias! Commodi deserunt adipisci nam quod iure cum itaque fugit repellendus consectetur magnam, molestias, dolor autem quae non esse a? Commodi, et repudiandae atque nemo esse ipsum possimus optio enim fugiat id porro quaerat recusandae soluta, error consectetur suscipit ad odit eos molestias laborum doloribus officia. Aliquam expedita, unde eos distinctio molestiae excepturi libero necessitatibus, sapiente, odio facere amet ad voluptates! Est necessitatibus placeat tenetur voluptate dolores ipsam facere voluptates voluptatum, nobis animi modi veritatis, hic fugiat dolore labore quos qui cupiditate esse!
        </div>
    )
}

export default Home
